//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:11 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalogQuery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterStringTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterStringTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="StandardValue" type="{http://ns.hr-xml.org/2007-04-15}FilterStringTypeEnumType"/>
 *         &lt;element name="NonStandardValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterStringTypeType", propOrder = {
    "standardValue",
    "nonStandardValue"
})
public class FilterStringTypeType {

    @XmlElement(name = "StandardValue")
    protected FilterStringTypeEnumType standardValue;
    @XmlElement(name = "NonStandardValue")
    protected String nonStandardValue;

    /**
     * Gets the value of the standardValue property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringTypeEnumType }
     *     
     */
    public FilterStringTypeEnumType getStandardValue() {
        return standardValue;
    }

    /**
     * Sets the value of the standardValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringTypeEnumType }
     *     
     */
    public void setStandardValue(FilterStringTypeEnumType value) {
        this.standardValue = value;
    }

    /**
     * Gets the value of the nonStandardValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonStandardValue() {
        return nonStandardValue;
    }

    /**
     * Sets the value of the nonStandardValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonStandardValue(String value) {
        this.nonStandardValue = value;
    }

}
