//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:11 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalogQuery;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.osf.romanvintonyak.WSDummy.AssessmentCatalogQuery package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserArea_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "UserArea");
    private final static QName _AssessmentCatalogQuery_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "AssessmentCatalogQuery");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.osf.romanvintonyak.WSDummy.AssessmentCatalogQuery
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityIdType }
     * 
     */
    public EntityIdType createEntityIdType() {
        return new EntityIdType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link AssessmentCatalogQueryType }
     * 
     */
    public AssessmentCatalogQueryType createAssessmentCatalogQueryType() {
        return new AssessmentCatalogQueryType();
    }

    /**
     * Create an instance of {@link UserAreaType }
     * 
     */
    public UserAreaType createUserAreaType() {
        return new UserAreaType();
    }

    /**
     * Create an instance of {@link SimpleExpressionOperatorType }
     * 
     */
    public SimpleExpressionOperatorType createSimpleExpressionOperatorType() {
        return new SimpleExpressionOperatorType();
    }

    /**
     * Create an instance of {@link SimpleExpressionType }
     * 
     */
    public SimpleExpressionType createSimpleExpressionType() {
        return new SimpleExpressionType();
    }

    /**
     * Create an instance of {@link FilterStringTypeType }
     * 
     */
    public FilterStringTypeType createFilterStringTypeType() {
        return new FilterStringTypeType();
    }

    /**
     * Create an instance of {@link EntityIdType.IdValue }
     * 
     */
    public EntityIdType.IdValue createEntityIdTypeIdValue() {
        return new EntityIdType.IdValue();
    }

    /**
     * Create an instance of {@link FilterType.FilterString }
     * 
     */
    public FilterType.FilterString createFilterTypeFilterString() {
        return new FilterType.FilterString();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "UserArea")
    public JAXBElement<UserAreaType> createUserArea(UserAreaType value) {
        return new JAXBElement<UserAreaType>(_UserArea_QNAME, UserAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssessmentCatalogQueryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "AssessmentCatalogQuery")
    public JAXBElement<AssessmentCatalogQueryType> createAssessmentCatalogQuery(AssessmentCatalogQueryType value) {
        return new JAXBElement<AssessmentCatalogQueryType>(_AssessmentCatalogQuery_QNAME, AssessmentCatalogQueryType.class, null, value);
    }

}
