//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:11 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalogQuery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimpleExpressionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleExpressionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Operator" type="{http://ns.hr-xml.org/2007-04-15}SimpleExpressionOperatorType"/>
 *         &lt;element name="ElementValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleExpressionType", propOrder = {
    "elementName",
    "operator",
    "elementValue"
})
public class SimpleExpressionType {

    @XmlElement(name = "ElementName", required = true)
    protected String elementName;
    @XmlElement(name = "Operator", required = true)
    protected SimpleExpressionOperatorType operator;
    @XmlElement(name = "ElementValue", required = true)
    protected String elementValue;

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementName(String value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleExpressionOperatorType }
     *     
     */
    public SimpleExpressionOperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleExpressionOperatorType }
     *     
     */
    public void setOperator(SimpleExpressionOperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the elementValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementValue() {
        return elementValue;
    }

    /**
     * Sets the value of the elementValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementValue(String value) {
        this.elementValue = value;
    }

}
