//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:11 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalogQuery;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimpleExpressionOperatorEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SimpleExpressionOperatorEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="equals"/>
 *     &lt;enumeration value="not equals"/>
 *     &lt;enumeration value="greater than"/>
 *     &lt;enumeration value="less than"/>
 *     &lt;enumeration value="like"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SimpleExpressionOperatorEnumType")
@XmlEnum
public enum SimpleExpressionOperatorEnumType {

    @XmlEnumValue("equals")
    EQUALS("equals"),
    @XmlEnumValue("not equals")
    NOT_EQUALS("not equals"),
    @XmlEnumValue("greater than")
    GREATER_THAN("greater than"),
    @XmlEnumValue("less than")
    LESS_THAN("less than"),
    @XmlEnumValue("like")
    LIKE("like");
    private final String value;

    SimpleExpressionOperatorEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimpleExpressionOperatorEnumType fromValue(String v) {
        for (SimpleExpressionOperatorEnumType c: SimpleExpressionOperatorEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
