//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for AdministrationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdministrationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdministrationNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsProctored" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TimeEnforcement">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="None"/>
 *               &lt;enumeration value="Partial"/>
 *               &lt;enumeration value="Complete"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EstimatedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AssessmentDelivery" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://ns.hr-xml.org/2007-04-15>AssessmentDeliveryTypes">
 *                 &lt;attribute name="schedulingRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdministrationInfoType", propOrder = {
    "administrationNotes",
    "isProctored",
    "timeEnforcement",
    "estimatedTime",
    "assessmentDelivery"
})
public class AdministrationInfoType {

    @XmlElement(name = "AdministrationNotes")
    protected String administrationNotes;
    @XmlElement(name = "IsProctored")
    protected Boolean isProctored;
    @XmlElement(name = "TimeEnforcement", required = true)
    protected String timeEnforcement;
    @XmlElement(name = "EstimatedTime")
    protected String estimatedTime;
    @XmlElement(name = "AssessmentDelivery")
    protected List<AdministrationInfoType.AssessmentDelivery> assessmentDelivery;

    /**
     * Gets the value of the administrationNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministrationNotes() {
        return administrationNotes;
    }

    /**
     * Sets the value of the administrationNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministrationNotes(String value) {
        this.administrationNotes = value;
    }

    /**
     * Gets the value of the isProctored property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsProctored() {
        return isProctored;
    }

    /**
     * Sets the value of the isProctored property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsProctored(Boolean value) {
        this.isProctored = value;
    }

    /**
     * Gets the value of the timeEnforcement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeEnforcement() {
        return timeEnforcement;
    }

    /**
     * Sets the value of the timeEnforcement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeEnforcement(String value) {
        this.timeEnforcement = value;
    }

    /**
     * Gets the value of the estimatedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimatedTime() {
        return estimatedTime;
    }

    /**
     * Sets the value of the estimatedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimatedTime(String value) {
        this.estimatedTime = value;
    }

    /**
     * Gets the value of the assessmentDelivery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assessmentDelivery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessmentDelivery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdministrationInfoType.AssessmentDelivery }
     * 
     * 
     */
    public List<AdministrationInfoType.AssessmentDelivery> getAssessmentDelivery() {
        if (assessmentDelivery == null) {
            assessmentDelivery = new ArrayList<AdministrationInfoType.AssessmentDelivery>();
        }
        return this.assessmentDelivery;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://ns.hr-xml.org/2007-04-15>AssessmentDeliveryTypes">
     *       &lt;attribute name="schedulingRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AssessmentDelivery {

        @XmlValue
        protected AssessmentDeliveryTypes value;
        @XmlAttribute(name = "schedulingRequired")
        protected Boolean schedulingRequired;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link AssessmentDeliveryTypes }
         *     
         */
        public AssessmentDeliveryTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link AssessmentDeliveryTypes }
         *     
         */
        public void setValue(AssessmentDeliveryTypes value) {
            this.value = value;
        }

        /**
         * Gets the value of the schedulingRequired property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSchedulingRequired() {
            return schedulingRequired;
        }

        /**
         * Sets the value of the schedulingRequired property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSchedulingRequired(Boolean value) {
            this.schedulingRequired = value;
        }

    }

}
