//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssessmentPersonDescriptorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssessmentPersonDescriptorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LegalIdentifiers" type="{http://ns.hr-xml.org/2007-04-15}AssessmentLegalIdentifiersType" minOccurs="0"/>
 *         &lt;element name="DemographicDescriptors" type="{http://ns.hr-xml.org/2007-04-15}AssessmentDemographicDescriptorsType" minOccurs="0"/>
 *         &lt;element name="BiologicalDescriptors" type="{http://ns.hr-xml.org/2007-04-15}AssessmentBiologicalDescriptorsType" minOccurs="0"/>
 *         &lt;element ref="{http://ns.hr-xml.org/2007-04-15}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssessmentPersonDescriptorsType", propOrder = {
    "legalIdentifiers",
    "demographicDescriptors",
    "biologicalDescriptors",
    "userArea"
})
public class AssessmentPersonDescriptorsType {

    @XmlElement(name = "LegalIdentifiers")
    protected AssessmentLegalIdentifiersType legalIdentifiers;
    @XmlElement(name = "DemographicDescriptors")
    protected AssessmentDemographicDescriptorsType demographicDescriptors;
    @XmlElement(name = "BiologicalDescriptors")
    protected AssessmentBiologicalDescriptorsType biologicalDescriptors;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * Gets the value of the legalIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentLegalIdentifiersType }
     *     
     */
    public AssessmentLegalIdentifiersType getLegalIdentifiers() {
        return legalIdentifiers;
    }

    /**
     * Sets the value of the legalIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentLegalIdentifiersType }
     *     
     */
    public void setLegalIdentifiers(AssessmentLegalIdentifiersType value) {
        this.legalIdentifiers = value;
    }

    /**
     * Gets the value of the demographicDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentDemographicDescriptorsType }
     *     
     */
    public AssessmentDemographicDescriptorsType getDemographicDescriptors() {
        return demographicDescriptors;
    }

    /**
     * Sets the value of the demographicDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentDemographicDescriptorsType }
     *     
     */
    public void setDemographicDescriptors(AssessmentDemographicDescriptorsType value) {
        this.demographicDescriptors = value;
    }

    /**
     * Gets the value of the biologicalDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentBiologicalDescriptorsType }
     *     
     */
    public AssessmentBiologicalDescriptorsType getBiologicalDescriptors() {
        return biologicalDescriptors;
    }

    /**
     * Sets the value of the biologicalDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentBiologicalDescriptorsType }
     *     
     */
    public void setBiologicalDescriptors(AssessmentBiologicalDescriptorsType value) {
        this.biologicalDescriptors = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

}
