//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AssessmentBiologicalDescriptorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssessmentBiologicalDescriptorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *           &lt;element name="MonthDayOfBirth" type="{http://www.w3.org/2001/XMLSchema}gMonthDay" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Age" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="AgeNumeric" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="AgeBand" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GenderCode" type="{http://ns.hr-xml.org/2007-04-15}GenderCodeType" minOccurs="0"/>
 *         &lt;element name="DisabilityInfo" type="{http://ns.hr-xml.org/2007-04-15}DisabilityInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssessmentBiologicalDescriptorsType", propOrder = {
    "dateOfBirth",
    "monthDayOfBirth",
    "age",
    "genderCode",
    "disabilityInfo"
})
public class AssessmentBiologicalDescriptorsType {

    @XmlElement(name = "DateOfBirth")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(name = "MonthDayOfBirth")
    @XmlSchemaType(name = "gMonthDay")
    protected XMLGregorianCalendar monthDayOfBirth;
    @XmlElement(name = "Age")
    protected AssessmentBiologicalDescriptorsType.Age age;
    @XmlElement(name = "GenderCode")
    protected BigInteger genderCode;
    @XmlElement(name = "DisabilityInfo")
    protected List<DisabilityInfoType> disabilityInfo;

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the monthDayOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMonthDayOfBirth() {
        return monthDayOfBirth;
    }

    /**
     * Sets the value of the monthDayOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMonthDayOfBirth(XMLGregorianCalendar value) {
        this.monthDayOfBirth = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentBiologicalDescriptorsType.Age }
     *     
     */
    public AssessmentBiologicalDescriptorsType.Age getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentBiologicalDescriptorsType.Age }
     *     
     */
    public void setAge(AssessmentBiologicalDescriptorsType.Age value) {
        this.age = value;
    }

    /**
     * Gets the value of the genderCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGenderCode() {
        return genderCode;
    }

    /**
     * Sets the value of the genderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGenderCode(BigInteger value) {
        this.genderCode = value;
    }

    /**
     * Gets the value of the disabilityInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disabilityInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisabilityInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisabilityInfoType }
     * 
     * 
     */
    public List<DisabilityInfoType> getDisabilityInfo() {
        if (disabilityInfo == null) {
            disabilityInfo = new ArrayList<DisabilityInfoType>();
        }
        return this.disabilityInfo;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="AgeNumeric" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="AgeBand" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ageNumeric",
        "ageBand"
    })
    public static class Age {

        @XmlElement(name = "AgeNumeric")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger ageNumeric;
        @XmlElement(name = "AgeBand")
        protected Object ageBand;

        /**
         * Gets the value of the ageNumeric property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAgeNumeric() {
            return ageNumeric;
        }

        /**
         * Sets the value of the ageNumeric property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAgeNumeric(BigInteger value) {
            this.ageNumeric = value;
        }

        /**
         * Gets the value of the ageBand property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAgeBand() {
            return ageBand;
        }

        /**
         * Sets the value of the ageBand property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAgeBand(Object value) {
            this.ageBand = value;
        }

    }

}
