//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * AssessmentPackageType represents the broader data model for 
 * an Assessment Package. This is used in AssessmentCatalog.xsd
 * 
 * 
 * <p>Java class for AssessmentPackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssessmentPackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PackageId" type="{http://ns.hr-xml.org/2007-04-15}EntityIdType"/>
 *         &lt;element name="PackageGroupId" type="{http://ns.hr-xml.org/2007-04-15}EntityIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PricingInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdministrationInfo" type="{http://ns.hr-xml.org/2007-04-15}AdministrationInfoType" minOccurs="0"/>
 *         &lt;element name="ResultInfo" type="{http://ns.hr-xml.org/2007-04-15}ResultInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Applicability" type="{http://ns.hr-xml.org/2007-04-15}AssessmentApplicabilityType"/>
 *         &lt;element ref="{http://ns.hr-xml.org/2007-04-15}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="validFrom" type="{http://ns.hr-xml.org/2007-04-15}AnyDateTimeNkNaType" />
 *       &lt;attribute name="validTo" type="{http://ns.hr-xml.org/2007-04-15}AnyDateTimeNkNaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssessmentPackageType", propOrder = {
    "packageId",
    "packageGroupId",
    "name",
    "description",
    "pricingInfo",
    "administrationInfo",
    "resultInfo",
    "applicability",
    "userArea"
})
public class AssessmentPackageType {

    @XmlElement(name = "PackageId", required = true)
    protected EntityIdType packageId;
    @XmlElement(name = "PackageGroupId")
    protected List<EntityIdType> packageGroupId;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "PricingInfo")
    protected String pricingInfo;
    @XmlElement(name = "AdministrationInfo")
    protected AdministrationInfoType administrationInfo;
    @XmlElement(name = "ResultInfo")
    protected List<ResultInfoType> resultInfo;
    @XmlElement(name = "Applicability", required = true)
    protected AssessmentApplicabilityType applicability;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;
    @XmlAttribute(name = "validFrom")
    protected String validFrom;
    @XmlAttribute(name = "validTo")
    protected String validTo;

    /**
     * Gets the value of the packageId property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIdType }
     *     
     */
    public EntityIdType getPackageId() {
        return packageId;
    }

    /**
     * Sets the value of the packageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIdType }
     *     
     */
    public void setPackageId(EntityIdType value) {
        this.packageId = value;
    }

    /**
     * Gets the value of the packageGroupId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageGroupId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackageGroupId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityIdType }
     * 
     * 
     */
    public List<EntityIdType> getPackageGroupId() {
        if (packageGroupId == null) {
            packageGroupId = new ArrayList<EntityIdType>();
        }
        return this.packageGroupId;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the pricingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingInfo() {
        return pricingInfo;
    }

    /**
     * Sets the value of the pricingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingInfo(String value) {
        this.pricingInfo = value;
    }

    /**
     * Gets the value of the administrationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrationInfoType }
     *     
     */
    public AdministrationInfoType getAdministrationInfo() {
        return administrationInfo;
    }

    /**
     * Sets the value of the administrationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrationInfoType }
     *     
     */
    public void setAdministrationInfo(AdministrationInfoType value) {
        this.administrationInfo = value;
    }

    /**
     * Gets the value of the resultInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultInfoType }
     * 
     * 
     */
    public List<ResultInfoType> getResultInfo() {
        if (resultInfo == null) {
            resultInfo = new ArrayList<ResultInfoType>();
        }
        return this.resultInfo;
    }

    /**
     * Gets the value of the applicability property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentApplicabilityType }
     *     
     */
    public AssessmentApplicabilityType getApplicability() {
        return applicability;
    }

    /**
     * Sets the value of the applicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentApplicabilityType }
     *     
     */
    public void setApplicability(AssessmentApplicabilityType value) {
        this.applicability = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidFrom(String value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidTo(String value) {
        this.validTo = value;
    }

}
