//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contactMethodLocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contactMethodLocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="office"/>
 *     &lt;enumeration value="vehicle"/>
 *     &lt;enumeration value="onPerson"/>
 *     &lt;enumeration value="home"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "contactMethodLocationType")
@XmlEnum
public enum ContactMethodLocationType {

    @XmlEnumValue("office")
    OFFICE("office"),
    @XmlEnumValue("vehicle")
    VEHICLE("vehicle"),
    @XmlEnumValue("onPerson")
    ON_PERSON("onPerson"),
    @XmlEnumValue("home")
    HOME("home");
    private final String value;

    ContactMethodLocationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContactMethodLocationType fromValue(String v) {
        for (ContactMethodLocationType c: ContactMethodLocationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
