//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.osf.romanvintonyak.WSDummy.AssessmentCatalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AreaCityCode_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "AreaCityCode");
    private final static QName _DunsNumber_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "DunsNumber");
    private final static QName _TTYTDD_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "TTYTDD");
    private final static QName _PersonName_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "PersonName");
    private final static QName _Telephone_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Telephone");
    private final static QName _WhenAvailable_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "WhenAvailable");
    private final static QName _NumericValue_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "NumericValue");
    private final static QName _InternetEmailAddress_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "InternetEmailAddress");
    private final static QName _NationalNumber_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "NationalNumber");
    private final static QName _Extension_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Extension");
    private final static QName _GenderCode_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "GenderCode");
    private final static QName _References_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "References");
    private final static QName _LanguageCode_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "LanguageCode");
    private final static QName _CountryCode_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "CountryCode");
    private final static QName _Mobile_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Mobile");
    private final static QName _Achievement_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Achievement");
    private final static QName _PersonDescriptors_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "PersonDescriptors");
    private final static QName _SpecifiedCompetencyReference_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "SpecifiedCompetencyReference");
    private final static QName _InternetWebAddress_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "InternetWebAddress");
    private final static QName _Pager_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Pager");
    private final static QName _SubscriberNumber_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "SubscriberNumber");
    private final static QName _Fax_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Fax");
    private final static QName _PostalAddress_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "PostalAddress");
    private final static QName _Location_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Location");
    private final static QName _FormattedNumber_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "FormattedNumber");
    private final static QName _CompetencyId_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "CompetencyId");
    private final static QName _CurrencyCode_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "CurrencyCode");
    private final static QName _InternetDomainName_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "InternetDomainName");
    private final static QName _InternationalCountryCode_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "InternationalCountryCode");
    private final static QName _Reference_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Reference");
    private final static QName _Use_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "Use");
    private final static QName _UserArea_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "UserArea1");
    private final static QName _AssessmentCatalog_QNAME = new QName("http://ns.hr-xml.org/2007-04-15", "AssessmentCatalog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.osf.romanvintonyak.WSDummy.AssessmentCatalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssociationType }
     * 
     */
    public AssociationType createAssociationType() {
        return new AssociationType();
    }

    /**
     * Create an instance of {@link OccupationalCategoryType }
     * 
     */
    public OccupationalCategoryType createOccupationalCategoryType() {
        return new OccupationalCategoryType();
    }

    /**
     * Create an instance of {@link DemographicDescriptorsType }
     * 
     */
    public DemographicDescriptorsType createDemographicDescriptorsType() {
        return new DemographicDescriptorsType();
    }

    /**
     * Create an instance of {@link LegalIdentifiersType }
     * 
     */
    public LegalIdentifiersType createLegalIdentifiersType() {
        return new LegalIdentifiersType();
    }

    /**
     * Create an instance of {@link AssessmentLegalIdentifiersType }
     * 
     */
    public AssessmentLegalIdentifiersType createAssessmentLegalIdentifiersType() {
        return new AssessmentLegalIdentifiersType();
    }

    /**
     * Create an instance of {@link EntityIdType }
     * 
     */
    public EntityIdType createEntityIdType() {
        return new EntityIdType();
    }

    /**
     * Create an instance of {@link AdministrationInfoType }
     * 
     */
    public AdministrationInfoType createAdministrationInfoType() {
        return new AdministrationInfoType();
    }

    /**
     * Create an instance of {@link StaffingSupportingMaterialsType }
     * 
     */
    public StaffingSupportingMaterialsType createStaffingSupportingMaterialsType() {
        return new StaffingSupportingMaterialsType();
    }

    /**
     * Create an instance of {@link OtherDescriptorsType }
     * 
     */
    public OtherDescriptorsType createOtherDescriptorsType() {
        return new OtherDescriptorsType();
    }

    /**
     * Create an instance of {@link AssessmentBiologicalDescriptorsType }
     * 
     */
    public AssessmentBiologicalDescriptorsType createAssessmentBiologicalDescriptorsType() {
        return new AssessmentBiologicalDescriptorsType();
    }

    /**
     * Create an instance of {@link BiologicalDescriptorsType }
     * 
     */
    public BiologicalDescriptorsType createBiologicalDescriptorsType() {
        return new BiologicalDescriptorsType();
    }

    /**
     * Create an instance of {@link AssessmentCatalogType }
     * 
     */
    public AssessmentCatalogType createAssessmentCatalogType() {
        return new AssessmentCatalogType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link PersonNameType.AlternateScript }
     * 
     */
    public PersonNameType.AlternateScript createPersonNameTypeAlternateScript() {
        return new PersonNameType.AlternateScript();
    }

    /**
     * Create an instance of {@link TelcomNumberType }
     * 
     */
    public TelcomNumberType createTelcomNumberType() {
        return new TelcomNumberType();
    }

    /**
     * Create an instance of {@link DunsNumberDataType }
     * 
     */
    public DunsNumberDataType createDunsNumberDataType() {
        return new DunsNumberDataType();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link FlexibleDatesType }
     * 
     */
    public FlexibleDatesType createFlexibleDatesType() {
        return new FlexibleDatesType();
    }

    /**
     * Create an instance of {@link AssociationType.Role }
     * 
     */
    public AssociationType.Role createAssociationTypeRole() {
        return new AssociationType.Role();
    }

    /**
     * Create an instance of {@link NumericValueType }
     * 
     */
    public NumericValueType createNumericValueType() {
        return new NumericValueType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link MobileTelcomNumberType }
     * 
     */
    public MobileTelcomNumberType createMobileTelcomNumberType() {
        return new MobileTelcomNumberType();
    }

    /**
     * Create an instance of {@link SpecifiedCompetencyReferenceType }
     * 
     */
    public SpecifiedCompetencyReferenceType createSpecifiedCompetencyReferenceType() {
        return new SpecifiedCompetencyReferenceType();
    }

    /**
     * Create an instance of {@link PersonDescriptorsType }
     * 
     */
    public PersonDescriptorsType createPersonDescriptorsType() {
        return new PersonDescriptorsType();
    }

    /**
     * Create an instance of {@link AchievementType }
     * 
     */
    public AchievementType createAchievementType() {
        return new AchievementType();
    }

    /**
     * Create an instance of {@link StringValue }
     * 
     */
    public StringValue createStringValue() {
        return new StringValue();
    }

    /**
     * Create an instance of {@link InternetDomainNameType }
     * 
     */
    public InternetDomainNameType createInternetDomainNameType() {
        return new InternetDomainNameType();
    }

    /**
     * Create an instance of {@link Associations }
     * 
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link UserAreaType }
     * 
     */
    public UserAreaType createUserAreaType() {
        return new UserAreaType();
    }

    /**
     * Create an instance of {@link Achievements }
     * 
     */
    public Achievements createAchievements() {
        return new Achievements();
    }

    /**
     * Create an instance of {@link ResultInfoType }
     * 
     */
    public ResultInfoType createResultInfoType() {
        return new ResultInfoType();
    }

    /**
     * Create an instance of {@link AssessmentDemographicDescriptorsType }
     * 
     */
    public AssessmentDemographicDescriptorsType createAssessmentDemographicDescriptorsType() {
        return new AssessmentDemographicDescriptorsType();
    }

    /**
     * Create an instance of {@link AssessmentApplicabilityType }
     * 
     */
    public AssessmentApplicabilityType createAssessmentApplicabilityType() {
        return new AssessmentApplicabilityType();
    }

    /**
     * Create an instance of {@link SourceTypeType }
     * 
     */
    public SourceTypeType createSourceTypeType() {
        return new SourceTypeType();
    }

    /**
     * Create an instance of {@link PositionPostingType }
     * 
     */
    public PositionPostingType createPositionPostingType() {
        return new PositionPostingType();
    }

    /**
     * Create an instance of {@link DistributionType }
     * 
     */
    public DistributionType createDistributionType() {
        return new DistributionType();
    }

    /**
     * Create an instance of {@link ContactMethodType }
     * 
     */
    public ContactMethodType createContactMethodType() {
        return new ContactMethodType();
    }

    /**
     * Create an instance of {@link AssessmentPersonDescriptorsType }
     * 
     */
    public AssessmentPersonDescriptorsType createAssessmentPersonDescriptorsType() {
        return new AssessmentPersonDescriptorsType();
    }

    /**
     * Create an instance of {@link PersonLegalIdType }
     * 
     */
    public PersonLegalIdType createPersonLegalIdType() {
        return new PersonLegalIdType();
    }

    /**
     * Create an instance of {@link AssessmentCompetencyReferenceType }
     * 
     */
    public AssessmentCompetencyReferenceType createAssessmentCompetencyReferenceType() {
        return new AssessmentCompetencyReferenceType();
    }

    /**
     * Create an instance of {@link DisabilityInfoType }
     * 
     */
    public DisabilityInfoType createDisabilityInfoType() {
        return new DisabilityInfoType();
    }

    /**
     * Create an instance of {@link AssessmentPackageType }
     * 
     */
    public AssessmentPackageType createAssessmentPackageType() {
        return new AssessmentPackageType();
    }

    /**
     * Create an instance of {@link OccupationalCategoryType.TaxonomyName }
     * 
     */
    public OccupationalCategoryType.TaxonomyName createOccupationalCategoryTypeTaxonomyName() {
        return new OccupationalCategoryType.TaxonomyName();
    }

    /**
     * Create an instance of {@link DemographicDescriptorsType.ChildrenInfo }
     * 
     */
    public DemographicDescriptorsType.ChildrenInfo createDemographicDescriptorsTypeChildrenInfo() {
        return new DemographicDescriptorsType.ChildrenInfo();
    }

    /**
     * Create an instance of {@link LegalIdentifiersType.MilitaryStatus }
     * 
     */
    public LegalIdentifiersType.MilitaryStatus createLegalIdentifiersTypeMilitaryStatus() {
        return new LegalIdentifiersType.MilitaryStatus();
    }

    /**
     * Create an instance of {@link LegalIdentifiersType.VisaStatus }
     * 
     */
    public LegalIdentifiersType.VisaStatus createLegalIdentifiersTypeVisaStatus() {
        return new LegalIdentifiersType.VisaStatus();
    }

    /**
     * Create an instance of {@link AssessmentLegalIdentifiersType.MilitaryStatus }
     * 
     */
    public AssessmentLegalIdentifiersType.MilitaryStatus createAssessmentLegalIdentifiersTypeMilitaryStatus() {
        return new AssessmentLegalIdentifiersType.MilitaryStatus();
    }

    /**
     * Create an instance of {@link EntityIdType.IdValue }
     * 
     */
    public EntityIdType.IdValue createEntityIdTypeIdValue() {
        return new EntityIdType.IdValue();
    }

    /**
     * Create an instance of {@link AdministrationInfoType.AssessmentDelivery }
     * 
     */
    public AdministrationInfoType.AssessmentDelivery createAdministrationInfoTypeAssessmentDelivery() {
        return new AdministrationInfoType.AssessmentDelivery();
    }

    /**
     * Create an instance of {@link StaffingSupportingMaterialsType.AttachmentReference }
     * 
     */
    public StaffingSupportingMaterialsType.AttachmentReference createStaffingSupportingMaterialsTypeAttachmentReference() {
        return new StaffingSupportingMaterialsType.AttachmentReference();
    }

    /**
     * Create an instance of {@link OtherDescriptorsType.List }
     * 
     */
    public OtherDescriptorsType.List createOtherDescriptorsTypeList() {
        return new OtherDescriptorsType.List();
    }

    /**
     * Create an instance of {@link AssessmentBiologicalDescriptorsType.Age }
     * 
     */
    public AssessmentBiologicalDescriptorsType.Age createAssessmentBiologicalDescriptorsTypeAge() {
        return new AssessmentBiologicalDescriptorsType.Age();
    }

    /**
     * Create an instance of {@link BiologicalDescriptorsType.Height }
     * 
     */
    public BiologicalDescriptorsType.Height createBiologicalDescriptorsTypeHeight() {
        return new BiologicalDescriptorsType.Height();
    }

    /**
     * Create an instance of {@link BiologicalDescriptorsType.Weight }
     * 
     */
    public BiologicalDescriptorsType.Weight createBiologicalDescriptorsTypeWeight() {
        return new BiologicalDescriptorsType.Weight();
    }

    /**
     * Create an instance of {@link AssessmentCatalogType.CatalogQueryStatus }
     * 
     */
    public AssessmentCatalogType.CatalogQueryStatus createAssessmentCatalogTypeCatalogQueryStatus() {
        return new AssessmentCatalogType.CatalogQueryStatus();
    }

    /**
     * Create an instance of {@link PostalAddressType.DeliveryAddress }
     * 
     */
    public PostalAddressType.DeliveryAddress createPostalAddressTypeDeliveryAddress() {
        return new PostalAddressType.DeliveryAddress();
    }

    /**
     * Create an instance of {@link PostalAddressType.Recipient }
     * 
     */
    public PostalAddressType.Recipient createPostalAddressTypeRecipient() {
        return new PostalAddressType.Recipient();
    }

    /**
     * Create an instance of {@link PersonNameType.FamilyName }
     * 
     */
    public PersonNameType.FamilyName createPersonNameTypeFamilyName() {
        return new PersonNameType.FamilyName();
    }

    /**
     * Create an instance of {@link PersonNameType.Affix }
     * 
     */
    public PersonNameType.Affix createPersonNameTypeAffix() {
        return new PersonNameType.Affix();
    }

    /**
     * Create an instance of {@link PersonNameType.AlternateScript.FamilyName }
     * 
     */
    public PersonNameType.AlternateScript.FamilyName createPersonNameTypeAlternateScriptFamilyName() {
        return new PersonNameType.AlternateScript.FamilyName();
    }

    /**
     * Create an instance of {@link PersonNameType.AlternateScript.Affix }
     * 
     */
    public PersonNameType.AlternateScript.Affix createPersonNameTypeAlternateScriptAffix() {
        return new PersonNameType.AlternateScript.Affix();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "AreaCityCode")
    public JAXBElement<String> createAreaCityCode(String value) {
        return new JAXBElement<String>(_AreaCityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DunsNumberDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "DunsNumber")
    public JAXBElement<DunsNumberDataType> createDunsNumber(DunsNumberDataType value) {
        return new JAXBElement<DunsNumberDataType>(_DunsNumber_QNAME, DunsNumberDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "TTYTDD")
    public JAXBElement<TelcomNumberType> createTTYTDD(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_TTYTDD_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "PersonName")
    public JAXBElement<PersonNameType> createPersonName(PersonNameType value) {
        return new JAXBElement<PersonNameType>(_PersonName_QNAME, PersonNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Telephone")
    public JAXBElement<TelcomNumberType> createTelephone(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_Telephone_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "WhenAvailable")
    public JAXBElement<String> createWhenAvailable(String value) {
        return new JAXBElement<String>(_WhenAvailable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumericValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "NumericValue")
    public JAXBElement<NumericValueType> createNumericValue(NumericValueType value) {
        return new JAXBElement<NumericValueType>(_NumericValue_QNAME, NumericValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "InternetEmailAddress")
    public JAXBElement<String> createInternetEmailAddress(String value) {
        return new JAXBElement<String>(_InternetEmailAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "NationalNumber")
    public JAXBElement<String> createNationalNumber(String value) {
        return new JAXBElement<String>(_NationalNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Extension")
    public JAXBElement<String> createExtension(String value) {
        return new JAXBElement<String>(_Extension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "GenderCode")
    public JAXBElement<BigInteger> createGenderCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_GenderCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferencesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "References")
    public JAXBElement<ReferencesType> createReferences(ReferencesType value) {
        return new JAXBElement<ReferencesType>(_References_QNAME, ReferencesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "LanguageCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguageCode(String value) {
        return new JAXBElement<String>(_LanguageCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "CountryCode")
    public JAXBElement<String> createCountryCode(String value) {
        return new JAXBElement<String>(_CountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MobileTelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Mobile")
    public JAXBElement<MobileTelcomNumberType> createMobile(MobileTelcomNumberType value) {
        return new JAXBElement<MobileTelcomNumberType>(_Mobile_QNAME, MobileTelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AchievementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Achievement")
    public JAXBElement<AchievementType> createAchievement(AchievementType value) {
        return new JAXBElement<AchievementType>(_Achievement_QNAME, AchievementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonDescriptorsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "PersonDescriptors")
    public JAXBElement<PersonDescriptorsType> createPersonDescriptors(PersonDescriptorsType value) {
        return new JAXBElement<PersonDescriptorsType>(_PersonDescriptors_QNAME, PersonDescriptorsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecifiedCompetencyReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "SpecifiedCompetencyReference")
    public JAXBElement<SpecifiedCompetencyReferenceType> createSpecifiedCompetencyReference(SpecifiedCompetencyReferenceType value) {
        return new JAXBElement<SpecifiedCompetencyReferenceType>(_SpecifiedCompetencyReference_QNAME, SpecifiedCompetencyReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "InternetWebAddress")
    public JAXBElement<String> createInternetWebAddress(String value) {
        return new JAXBElement<String>(_InternetWebAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Pager")
    public JAXBElement<TelcomNumberType> createPager(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_Pager_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "SubscriberNumber")
    public JAXBElement<String> createSubscriberNumber(String value) {
        return new JAXBElement<String>(_SubscriberNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Fax")
    public JAXBElement<TelcomNumberType> createFax(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_Fax_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostalAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "PostalAddress")
    public JAXBElement<PostalAddressType> createPostalAddress(PostalAddressType value) {
        return new JAXBElement<PostalAddressType>(_PostalAddress_QNAME, PostalAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "FormattedNumber")
    public JAXBElement<String> createFormattedNumber(String value) {
        return new JAXBElement<String>(_FormattedNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "CompetencyId")
    public JAXBElement<EntityIdType> createCompetencyId(EntityIdType value) {
        return new JAXBElement<EntityIdType>(_CompetencyId_QNAME, EntityIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "CurrencyCode")
    public JAXBElement<String> createCurrencyCode(String value) {
        return new JAXBElement<String>(_CurrencyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternetDomainNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "InternetDomainName")
    public JAXBElement<InternetDomainNameType> createInternetDomainName(InternetDomainNameType value) {
        return new JAXBElement<InternetDomainNameType>(_InternetDomainName_QNAME, InternetDomainNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "InternationalCountryCode")
    public JAXBElement<String> createInternationalCountryCode(String value) {
        return new JAXBElement<String>(_InternationalCountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Reference")
    public JAXBElement<ReferenceType> createReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Reference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "Use")
    public JAXBElement<String> createUse(String value) {
        return new JAXBElement<String>(_Use_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "UserArea1")
    public JAXBElement<UserAreaType> createUserArea(UserAreaType value) {
        return new JAXBElement<UserAreaType>(_UserArea_QNAME, UserAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssessmentCatalogType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2007-04-15", name = "AssessmentCatalog")
    public JAXBElement<AssessmentCatalogType> createAssessmentCatalog(AssessmentCatalogType value) {
        return new JAXBElement<AssessmentCatalogType>(_AssessmentCatalog_QNAME, AssessmentCatalogType.class, null, value);
    }

}
