//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonLegalIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonLegalIdType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ns.hr-xml.org/2007-04-15}EntityIdType">
 *       &lt;attribute name="countryCode" type="{http://ns.hr-xml.org/2007-04-15}CountryCodeType" />
 *       &lt;attribute name="jurisdiction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="issuingRegion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="idSource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonLegalIdType")
public class PersonLegalIdType
    extends EntityIdType
{

    @XmlAttribute(name = "countryCode")
    protected String countryCode;
    @XmlAttribute(name = "jurisdiction")
    protected String jurisdiction;
    @XmlAttribute(name = "issuingRegion")
    protected String issuingRegion;
    @XmlAttribute(name = "documentType")
    protected String documentType;
    @XmlAttribute(name = "idSource")
    protected String idSource;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurisdiction() {
        return jurisdiction;
    }

    /**
     * Sets the value of the jurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurisdiction(String value) {
        this.jurisdiction = value;
    }

    /**
     * Gets the value of the issuingRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuingRegion() {
        return issuingRegion;
    }

    /**
     * Sets the value of the issuingRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuingRegion(String value) {
        this.issuingRegion = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the idSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSource() {
        return idSource;
    }

    /**
     * Sets the value of the idSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSource(String value) {
        this.idSource = value;
    }

}
