//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SourceEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Job Board"/>
 *     &lt;enumeration value="Staffing Agency"/>
 *     &lt;enumeration value="Intermediary"/>
 *     &lt;enumeration value="Referrer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SourceEnumType")
@XmlEnum
public enum SourceEnumType {

    @XmlEnumValue("Job Board")
    JOB_BOARD("Job Board"),
    @XmlEnumValue("Staffing Agency")
    STAFFING_AGENCY("Staffing Agency"),
    @XmlEnumValue("Intermediary")
    INTERMEDIARY("Intermediary"),
    @XmlEnumValue("Referrer")
    REFERRER("Referrer");
    private final String value;

    SourceEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceEnumType fromValue(String v) {
        for (SourceEnumType c: SourceEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
