//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 02:36:58 PM EEST 
//


package com.osf.romanvintonyak.WSDummy.AssessmentCatalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecifiedCompetencyReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecifiedCompetencyReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.hr-xml.org/2007-04-15}CompetencyId"/>
 *         &lt;element name="ProficencyLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecifiedCompetencyReferenceType", propOrder = {
    "competencyId",
    "proficencyLevel"
})
@XmlSeeAlso({
    AssessmentCompetencyReferenceType.class
})
public class SpecifiedCompetencyReferenceType {

    @XmlElement(name = "CompetencyId", required = true)
    protected EntityIdType competencyId;
    @XmlElement(name = "ProficencyLevel")
    protected String proficencyLevel;

    /**
     * Gets the value of the competencyId property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIdType }
     *     
     */
    public EntityIdType getCompetencyId() {
        return competencyId;
    }

    /**
     * Sets the value of the competencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIdType }
     *     
     */
    public void setCompetencyId(EntityIdType value) {
        this.competencyId = value;
    }

    /**
     * Gets the value of the proficencyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProficencyLevel() {
        return proficencyLevel;
    }

    /**
     * Sets the value of the proficencyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProficencyLevel(String value) {
        this.proficencyLevel = value;
    }

}
